name: Release

on:
  push:
    branches: [main]

permissions:
  contents: write
  pull-requests: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: true
          token: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: npm

      - run: npm ci

      - run: npm run lint && npm run typecheck && npm test && npm run build

      - uses: changesets/action@v1
        with:
          version: npm run version
          commit: "chore: release and update submodule"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}